### ISSUE TITLE
privileged and custom binaries?

### ISSUE THREAD

**Issue by adrianlzt** [lejmr/iredmail-docker#12]
Why the container needs the --privileged option?
And why are you copying custom binaries?
```
COPY ./uname /bin/uname
```
Not really safe to trust a container in privileged mode with unkowns binaries.

**Comment by lejmr** [comment]
You need it for running container on system ports.
It is a custom script: https://github.com/lejmr/iredmail-docker/blob/master/mysql/uname
It is a workaround for building container and certain domain name. Installation would not work with the non-fqdn hostname which docker instance has by default.

Indeed that could be reverted with this RUN; https://github.com/lejmr/iredmail-docker/blob/master/mysql/Dockerfile#L53

Do you want me send a pull-request?

**Comment by adrianlzt** [comment]
And why not use EXPOSE for the ports?

**Comment by lejmr** [comment]
Please look at the last line.

**Comment by lejmr** [comment]
Please look at the last line.

**Comment by nazar-pc** [comment]
Still don't understand why privileged mode is needed. I'm running custom container with iRedMail and without privileged mode for a few years now and looking for pre-made image that will allow easier upgrades.

So can you explain why exactly privileged mode is needed? Ports can be exposed without issues in non-privileged mode.

**Comment by nazar-pc** [comment]
I'm in process of examining sources already. But since in readme you're using `--privileged`, it would be nice to the complete list of things that require this option to be set and what would happen if the option is not specified. It is a dangerous option and there should be a pretty strong justification for it to be required.

**Comment by lejmr** [comment]
The only thing were ports <= 1024 at the time when I added it.

**Comment by nazar-pc** [comment]
Well, then it can be removed, since you already use `-p 80:80` and the same can be applied to any other port.

**Comment by twelsby** [comment]
I can't see why privileged mode is required.  I have run without it for some time without any apparent ill effect. If its sole purpose was to allow ports to be exposed then it is certainly no longer required as there is a way to achieve this without giving the container full host access.  Privileged mode might work, but it is really meant for other things, and is certainly not the best way to access host ports.

Per the documentation (see [publish or expose port](https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose)), the proper way to expose container ports to the host is via the `run` command arguments `-p` or `--expose`, or the docker-compose `ports` directive.  The recommended `run` invocation (in the README) already does this for 80 and 433, but this really should be extended to the full suite of mail server ports i.e. 25, 110, 143, 587, 993 and 995.

The `EXPOSE` directive in Dockerfile does not expose ports to the host, rather it serves as indication of the image authors intent (see [EXPOSE](https://docs.docker.com/engine/reference/builder/#expose)).  It does nothing unless the user of the image publishes the ports using `-p`, `--expose` or `-P` (which maps random high port numbers on the host to the ports indicated in the `EXPOSE` directive). There is no way to permit access to *host* ports in the Dockerfile -- this can only be done at runtime.

Note that removing `--privileged` mode does not require any changes to Dockerfile, or any other build files.  The only thing that really needs to change is the README.  The README should also be modified to add the mail ports to the list of ports that are published via the `run` command.

**Comment by nazar-pc** [comment]
The only thing that will not work properly I can think of is iptables rules in fail2ban, but:
* it is possible to add some capabilities to the container instead of full `--privileged` just for this
* I'm not sure if it is a really good idea to allow container to change iptables rules and how it will coexist with host system

**Comment by twelsby** [comment]
I was going to raise an addition issue because currently fail2ban is broken.  The runit script waits for `/var/logs/dovecot.log` but this is not the correct log filename, which should be `/var/log/dovecot/dovecot.log`.  Hence the runit script never starts.  This results in CRON email relating to a logrotate post run script failing when it attempts to restart fail2ban.  This probably needs to go in a separate issue however.

When I fixed the above issue I was hit with a plethora of fail2ban errors related to the iptables problem you identified (I am running without privileged mode).  I never got around to working out the cause because it got me to question why we even have fail2ban or iptables in the build to begin with.  My opinion is that these should be handled in the host, otherwise every container needs to have its own fail2ban/iptables implementation.  This really deserves its own issue as well.

Yet another issue that arises from all this is that of logging.  Logging is also broken at the moment (currently most of the mail logs are *not* captured by docker).  If fail2ban/iptables are to be moved to the host then full mail logging would need to be captured by docker and integrated into the host logs.  This also deserves its own issue.
