### ISSUE TITLE
There are a configuration problems with domain, hostname and passwords

### ISSUE THREAD

**Issue by TitanFighter** [lejmr/iredmail-docker#14]
Hi. Thanks for this repository!

I found the next issues:
1) Here there is just one example of config from `iRedMail.tips` (the same can be seen in one of emails which postmaster receives after installation).

```
Roundcube webmail: /opt/www/roundcubemail-1.3.3
* Config file: /opt/www/roundcubemail-1.3.3/config
* Web access:
- URL: http://HOSTNAME.DOMAIN/mail/ (will be redirected to https:// site)  <<----
- URL: https://HOSTNAME.DOMAIN/mail/ (secure connection)  <<----
- Username: postmaster@`DOMAIN`  <<----
- Password: FUPASSWORD
* SQL database account:
- Database name: roundcubemail
- Username: roundcube
- Password: TEMP_RCM_DB_PASSWD  <<----
```

2) Also if I check `hostname -f` inside container I see `HOSTNAME.DOMAIN`.
3) In IredAdmin the field Hostname shows `1b0e2800cb1c`.
4) Docker's logs shows `mv: cannnot stat '/var/lib/dkim/DOMAIN.pem': No such file or directory`. I checked this path and instead of `DOMAIN.pem` I see actually `myrealdomain.com.pem`

**Comment by InfiniteLukeOne** [comment]
I stumbled across similar problems in my fork. Not all instances of temporary passwords and domains in image creation are replaced when a container is created and running. Maybe I can look into creating a pull request with the ones I fixed, but iRedMail.tips and the initial mail are not part of the fixes.

**Comment by twelsby** [comment]
The solution to these problems is:
1. Patch the relevant emails and tip files on first boot
2/3. Rewrite the hostname logic so that we are not fighting docker so much (the hacked hostname solves the problem of iredmail complaining about the lack of a FQDN  but creates others)
4. What is happening is that the service init script amavis.sh contains a sed command that attempts to patch the line starting that sets the domain DKIM key, but because the substitution command lacks 'g' at the end it only replaces the first instance of DOMAIN, which leaves the actual DKIM key file as 'DOMAIN.pem'.  This causes amavis.sh to fail further on and exit with a non-zero, which causes it to be called again a second time.  This time the sed command successfully changes 'DOMAIN.pem' (because the first instance of DOMAIN on that line was changed on the first pass), but now the mv command fails (because the file was moved on the first pass).  The solution is to add a single 'g'.

I have implemented all of these fixes and they appear to work will. I will submit a pull request shortly.
