### ISSUE TITLE
force to use 587 instead of 25

### ISSUE THREAD

**Issue by wireless-road** [lejmr/iredmail-docker#52]
Hi!
Thank you for great docker container!
Trying to run it on digitalocean that doesn't allow to use port 25.
So in `/var/log/mail.log` I see following:
` postfix/smtp[2496]: 56DCC8DC25A: to=<test-2etp7@mail-tester.com>, relay=none, delay=530, delays=500/0.02/30/0, dsn=4.4.1, status=deferred (connect to mail-tester.com[94.23.206.89]:25: Connection timed out)`
So, how to force iredmail to use 587 port instead of 25 ?

**Comment by lejmr** [comment]
Port 587 (submission) is enabled by default. Make sure you have your iptables set properly. You can use command `ss -lt` in order to find what ports you OS is listening.

The example only opens HTTP interface for webmail. However, for using your container as a service, you need to forward all ports ideally (80 443 25 587 110 143 993 995). When you are -p these ports, you can even change mapping of these ports.
