### ISSUE TITLE
[Questions]   First installation questions

### ISSUE THREAD

**Issue by Ryu945** [lejmr/iredmail-docker#55]
1)  What are SOGO_WORKERS and how do I know what I should set the value to?  I have read that SOGO is some program to help email clients connect so you don't have to use web GUI.

2)  Is it required to run this container as privledged?

3)  What are the options available for the time zone parameter?

4)  Will mounting this volume remove the need for the time zone command?
`/etc/localtime:/etc/localtime:ro`

5)  Do I need more then ports 443 and 80 setup in NGINX.  I noticed the docker container exposes a bunch of ports.

https://github.com/lejmr/iredmail-docker/issues/11

`EXPOSE 80 443 25 587 110 143 993 995`

edit:

6) Tried things out.  I am getting this problem.  https://github.com/lejmr/iredmail-docker/issues/37

7)  The problem I seem to be having is the NGINX proxy I am using likes to communicate over http with containers and this one likes redirects to https when it sees http so it creates an endless loop.

edit2:
I got this working so that I am taken to a login page.   I still don't know what ports I need to have my NGINX proxy setup.  Right not I have only 443 and 80.

**Comment by InfiniteLukeOne** [comment]
Maybe not relevant anymore but since this issue was mentioned, here are some answers:

2. Priviledged should not be required. I run my container without it.
3. Don't really know but in a quick search I found this list: https://docs.diladele.com/docker/timezones.html
5. I have all of the exposed ports mapped and I think they are all required for SMTP (25, 587), IMAP (143, 993) and POP (110, 995)

**Comment by Ryu945** [comment]
Thankyou for the details.  I just needed to be sure on what ports were really needed.  I did find out from much trial and error that the Ngnix image I was using is only really setup to work for ports 443 and 80 automatically and I have to manually configure anything else.
